### PR TITLE
Remove error wording around install-jdk

### PR DESCRIPTION
**Pull request by jyksnw**
Removed wording about error on running jdk.install twice since latest version of install-jdk resolved this issue.

### CODE REVIEW

**Comment by hx2A** [comment]
> Removed wording about error on running jdk.install twice since latest version of install-jdk resolved this issue.

Fantastic, thank you so much for the fix to your very useful library!

Just out of curiosity, how did you find out about py5?

**Comment by hx2A** [comment]
thank you, @jyksnw , I just deployed the fix to the website.

**Comment by jyksnw** [comment]
Hi @hx2A, py5 came to my attention through a separate bug request I received from @villares looking to add support for aarch64 to the library. I am actually super interested in what py5 does and am hoping to play around with it a bit over the coming days.

Thanks for the merge!

**Comment by hx2A** [comment]
> am actually super interested in what py5 does and am hoping to play around with it a bit over the coming days.

Python and Java work very well together. Have fun experimenting and show us what you come up with!

**Pull request merged**
