### PR TITLE
exploring some quick setup wording options

### PR DESCRIPTION
**Pull request by villares**
Just to start a conversation about this...

### CODE REVIEW

**Comment by villares** [comment]
Questions:
- Should this text say Java 17+ instead of 17?

- My prime motivation to start this discussion was to bring some of the info on how to install the py5 Jupyter kernels directly into the quick setup instructions. Then I overstepped and tried to streamline the `pip install py5[jupyter]` part because, even if it is good information to have the details seems a bit distracting on quick setup. Then lot's of questions started to pop... could the py5jupyter package install the kernels automatically? Would that be bad form?

I keep thinking of more elaborate, and harder to maintain, installation scripts...  there are days that I dream of a single conda recipe that could install and configure *everything* JDK, Thonny, Kernels maybe just asking some questions while it proceeds.

**Comment by hx2A** [comment]
> Should this text say Java 17+ instead of 17?

Sure, Java 17+ should be OK. Was there a Java 19 issue in the other issue you opened and then closed? Newer versions of Java after 17 should all work fine, but I haven't tested all of them. The JVM will see that the py5 jars are compiled with Java 17 and will adapt to that level.

> pip install py5[jupyter]

I might have had the `pip install py5[jupyter]` in there at one point but I vaguely recall you suggesting I should not have that? I could be misremembering. In any case, I'm always open to new ideas about how to make the install instructions more accessible to beginners.

> could the py5jupyter package install the kernels automatically? Would that be bad form?

No, because there are some options one can use to install the kernels to various locations. The documentation recommends using the `--sys-prefix` but that is optional. It drives me up the wall when Jupyter presents me with kernel choices that cannot work for the environment I am in. Others might feel differently though.

> I keep thinking of more elaborate, and harder to maintain, installation scripts... there are days that I dream of a single conda recipe that could install and configure everything JDK, Thonny, Kernels maybe just asking some questions while it proceeds.

What about Docker? Or something similar?

**Comment by villares** [comment]
I can't remember exactly what was our dicussion about pip install py5[jupyper], but I'd vote for simpler instructions in this context. How do you think this is going?

Docker sounds frigthening and another source of complexity. I could be wrong...

**Comment by hx2A** [comment]
> I can't remember exactly what was our dicussion about pip install py5[jupyper], but I'd vote for simpler instructions in this context. How do you think this is going?

Yes, simpler is better, but I am not always the best judge for what is simpler. I will review the PR later when I get home (currently at the United Nations right now)

> Docker sounds frigthening and another source of complexity.

No, that's accurate, and that's unfortunate, because it would be amazing if it was not.

**Comment by hx2A** [comment]
Sorry I overlooked this PR. I'm getting caught up with things and will get to it this week.

**Review by hx2A — COMMENTED** [review]
some minor changes to the pr

**Comment by hx2A** [comment]
OK, @villares , I was able to merge this PR. I tried to make a few changes and push to your PR but either I did something wrong or I didn't have permission to do so. In any case, I made some adjustments and now have everything straightened out in git and pushed to the prod website.

**Pull request merged**
