### PR TITLE
Note about g -> get_graphics()

### PR DESCRIPTION
**Pull request by villares**
I'm not sure if this would be excessive, maybe?

### CODE REVIEW

**Comment by hx2A** [comment]
That's a good addition, but I think you meant `/reference/sketch_get_graphics` for the link.

**Comment by hx2A** [comment]
Somewhere in here I'm supposed to be able to change that file in your PR but I don't see it. Can you make that change and push it?

**Comment by villares** [comment]
ops! yes, thanks, did it.

Em qui., 8 de fev. de 2024 às 20:06, Jim ***@***.***>
escreveu:

**Comment by hx2A** [comment]
Thank you! The update is now on the prod website.

**Pull request merged**
